config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.core:
      branch: 106-improve-SQAaaS-score
      repo: https://github.com/cessda/cessda.cmv.core
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.core git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cream-molly.sh
        container: qc.acc_goopy-saffron-dachsbracke
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.core find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-green-cheetah.sh
        container: qc.doc_homely-chestnut-vole
      github.com/cessda/cessda.cmv.core git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-aquamarine-stoat.sh
        container: qc.doc_wheezy-wisteria-buffalo
      github.com/cessda/cessda.cmv.core markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-champagne-dogfish.sh
        container: qc.doc_messy-olive-macaw
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.core licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-razzmatazz-blue.sh
        container: qc.lic_fuzzy-auburn-urchin
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.core checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-tomato-chimpanzee.sh
        container: qc.sty_greasy-malachite-moorhen
      github.com/cessda/cessda.cmv.core jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-mustard-lobster.sh
        container: qc.sty_wheezy-brass-peccary
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.core get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cobalt-dugong.sh
        container: qc.ver_scaly-chartreuse-chinook
timeout: 5400
