config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.core:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.core
    github.com/cessda/cessda.cmv.documentation:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.documentation
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.core git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cornflower-terrier.sh
        container: qc.acc_slimy-mauve-squid
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.documentation find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-maroon-dunker.sh
        container: qc.doc_lovely-wheat-starfish
      github.com/cessda/cessda.cmv.documentation git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-teal-sloth.sh
        container: qc.doc_skimpy-lime-wolf
      github.com/cessda/cessda.cmv.documentation markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-malachite-tamarin.sh
        container: qc.doc_skanky-sepia-barb
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.core licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-salmon-bee.sh
        container: qc.lic_sleazy-celadon-salamander
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.core cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-chestnut-opossum.sh
        container: qc.met_seedy-linen-fox
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.core checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cinnabar-dog.sh
        container: qc.sty_muzzy-denim-squirrel
      github.com/cessda/cessda.cmv.core jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-copper-crocodile.sh
        container: qc.sty_woolly-turquoise-ant
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.core get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-firebrick-frise.sh
        container: qc.ver_chummy-grey-chicken
timeout: 5400
