config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.core:
      branch: 107-replace-references-to-Bitbucket
      repo: https://github.com/cessda/cessda.cmv.core
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.core git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-charcoal-mandrill.sh
        container: qc.acc_muzzy-brown-eagle
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.core find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-lime-ferret.sh
        container: qc.doc_scummy-smalt-pinscher
      github.com/cessda/cessda.cmv.core git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-charcoal-mist.sh
        container: qc.doc_snappy-amethyst-chimpanzee
      github.com/cessda/cessda.cmv.core markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-ochre-octopus.sh
        container: qc.doc_woolly-dandelion-scorpion
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.core licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-asparagus-centipede.sh
        container: qc.lic_whiny-plum-owl
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.core cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cyan-dachshund.sh
        container: qc.met_surly-goldenrod-flounder
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.core checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-blue-flamingo.sh
        container: qc.sty_fuzzy-black-urchin
      github.com/cessda/cessda.cmv.core jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-magnolia-millipede.sh
        container: qc.sty_freaky-violet-robin
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.core get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-teal-whale.sh
        container: qc.ver_bluesy-crimson-baboon
timeout: 5400
